### ISSUE TITLE
Published Gem is empty?

### ISSUE THREAD

**Issue by chkelly** [manybrain/mailinator-ruby-client#1]
The gem published [here](https://rubygems.org/gems/mailinator_client) doesn't appear to be built properly and cannot be imported. It shows as being 4.5KB in size. I checked the gem and the directory post installation is actually empty.

Pulling this gem down manually and doing a gem unpack also results in an empty directory. 

I built master and ended up with an 13KB gem that when installed worked.

```
$ gem build mailinator_client.gemspec
  Successfully built RubyGem
  Name: mailinator_client
  Version: 1.0.0
  File: mailinator_client-1.0.0.gem

$ ls -hl mailinator_client-1.0.0.gem
-rw-r--r--  1 ckelly  staff    13K Oct 14 16:29 mailinator_client-1.0.0.gem


$ gem install mailinator_client-1.0.0.gem
Successfully installed mailinator_client-1.0.0
Parsing documentation for mailinator_client-1.0.0
Done installing documentation for mailinator_client after 0 seconds
1 gem installed


$ irb
2.6.5 :001 > require 'mailinator_client'
=> true
```

**Comment by manybrain** [comment]
we just pushed a fix. please try again

**Comment by chkelly** [comment]
@manybrain Confirmed that 1.0.1 is installing properly
