### ISSUE TITLE
HTTParty vulnerability

### ISSUE THREAD

**Issue by Fuzzwump** [manybrain/mailinator-ruby-client#2]
A dependency update is needed, HTTParty has a known vulnerability, the version should be updated to at least 0.2.0

**Comment by marianmelnychuk** [comment]
> A dependency update is needed, HTTParty has a known vulnerability, the version should be updated to at least 0.2.0

Thanks for your remark. 
Did you mean 0.20.0 or 0.2.0?
Because our current version in this project is 0.14.0

**Comment by willgiesbarton** [comment]
Hi Marian, it looks like the most recent version of HTTParty is 0.21.0 https://rubygems.org/gems/httparty/versions/0.21.0
Thanks!

**Comment by willgiesbarton** [comment]
I've opened a PR with the dependency update https://github.com/manybrain/mailinator-ruby-client/pull/3

**Comment by marianmelnychuk** [comment]
> I've opened a PR with the dependency update #3

thank you so much. 
Your PR is merged
